fondecyt/urls.py
from django.urls import path
from fondecyt import views
app_name = 'fondecyt'

urlpatterns = [
    path('', views.home, name='home'),
    path('proyecto/', views.proyectos, name="proyecto"),
    path('instituciones/', views.instituciones, name="instituciones"),
    path('equipo/', views.equipo, name="equipo"),
    path('equipo/<int:id>', views.detallesEquipo, name="integrante"),
    path('colaboradores/', views.colaboradores, name="colaboradores"),
    path('colabodores/<int:id>', views.detallesColaborador, name="colaborador"),
    path('noticias/', views.noticias, name="noticias"),
    path('noticia/<int:id>', views.detalleNoticia, name="noticia"),
    path('productos/', views.productos, name="productos"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fondecyt.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fondecyt/models.py
from django.db import models
from django.contrib.auth.models import User

class Universidad(models.Model):
    name = models.CharField(max_length=80)
    desc = models.TextField(max_length=200, null=True)
    web = models.URLField(max_length=200, null=True)
    photo = models.ImageField(upload_to='instituciones/', blank=True, null=True)

    def __str__(self):
        return self.name

class Persona(models.Model):
    name = models.CharField(max_length=50)
    lastname = models.CharField(max_length=30)
    universidad = models.ForeignKey(Universidad, on_delete=models.CASCADE, default=1)
    resumen = models.TextField(max_length=3000)
    info = models.TextField(max_length=170, default=0)
    photo = models.ImageField(upload_to='equipo/', blank=True, null=True)
    cargos = (
		('In', 'Integrante'),
		('Co', 'Colaborador')
		)
    cargo = models.CharField(max_length=10, choices=cargos, default=0)
    #username = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Noticia(models.Model):
    autor = models.ForeignKey(Persona, on_delete=models.CASCADE, default=1)
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=3000)
    cabecera = models.TextField(max_length=250)
    contenido = models.TextField()
    photo = models.ImageField(upload_to='noticias/', blank=True, null=True)

    def __str__(self):
        return self.titulo


class Document(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(max_length=255, blank=True)
    autor = models.ForeignKey(Persona, on_delete=models.CASCADE, default=1)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

fondecyt/views.py
from django.shortcuts import render
from fondecyt.models import (
    Noticia,
    Universidad,
    Persona,
    Document
    )

def home(request):
    data = {}
    template_name = 'home.html'
    data['noticias'] = Noticia.objects.order_by('-id')[:2]

    return render(request, template_name, data)

def proyectos(request):
    data = {}
    template_name = 'proyecto.html'

    return render(request, template_name, data)

def instituciones(request):
    data = {}
    template_name = 'instituciones.html'
    data['instituciones'] = Universidad.objects.all().exclude(id=6)


    return render(request, template_name, data)

def equipo(request):
    data = {}
    template_name = 'equipo.html'
    data['equipo'] = Persona.objects.filter(cargo='In')
    return render(request, template_name, data)

def colaboradores(request):
    data = {}
    template_name = 'colaboradores.html'
    data['colaboradores'] = Persona.objects.filter(cargo='Co')


    return render(request, template_name, data)

def detallesEquipo(request, id):
    data = {}
    template_name = 'integrante.html'
    data['persona'] = Persona.objects.get(pk=id)
    if data['persona'].photo:
        data['foto'] = data['persona'].photo.url
    else:
        pass

    return render(request, template_name, data)

def detallesColaborador(request, id):
    data = {}
    template_name = 'integrante.html'
    data['persona'] = Persona.objects.get(pk=id)
    if data['persona'].photo:
        data['foto'] = data['persona'].photo.url
    else:
        pass

    return render(request, template_name, data)


def productos(request):
    data = {}
    template_name = 'productos.html'

    data['productos'] = Document.objects.all()
    print(data['productos'][0].document.url)

    return render(request, template_name, data)

def noticias(request):
    data = {}
    template_name = 'noticias.html'
    data['noticias'] = Noticia.objects.all()
    cant = Noticia.objects.count()
    for i in range(0,cant):
        if(data['noticias'][i].photo):
            data['noticias'][i].photo = data['noticias'][i].photo
        else:
            data['noticias'][i].photo = 'fondecyt/images/news.jpg'

    return render(request, template_name, data)

def detalleNoticia(request, id):
    data = {}
    template_name = 'noticia.html'
    data['noticia'] = Noticia.objects.get(pk=id)
    if data['noticia'].photo:
        data['foto'] = data['noticia'].photo.url
        contenido = (data['noticia'].contenido).split("\n")
        data['parrafos'] = contenido
    else:
        contenido = (data['noticia'].contenido).split("\n")
        data['parrafos'] = contenido
 

    return render(request, template_name, data)

fondecyt/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/686111fdd6.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'fondecyt/css/style.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=NotoSansJP" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css">
</head>

<body>
  {% include 'partials/navbar.html' %}
  {% block partials %}
  {% endblock %}
  <div class="container">
    {% block content_body %}

    {% endblock %}
  </div>
  {% block parciales %}
  {% endblock %}
  <div class="jumbotron jumbotron-fluid mt-4">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-12">
          <h6>Fondecyt INI 11180044.</h6>
          <img class="navbar-brand" src="{% static 'fondecyt/images/LOGO-FONDECYT.png' %}" width="400">
          <p class="lead" style="font-size: 15px; text-align: justify;">
            <hr>
            Este Proyecto fue financiado por el Ministerio de Educación de Chile, mediante el Fondo nacional de desarrollo cientifico y tecnologico
          </p>
          <p class="lead" style="font-size: 15px; text-align: justify;">(Código Proyecto; Fondecyt INI 11180044, año 2020)</p>
        </div>
        <div class="col-lg-6 col-12">
          <i class="fas fa-phone-square-alt mt-5" style="color: green; text-align: right; font-size: 25px;"><p style="display: inline; color: black; font-family: Oswald; font-size: 18px;" class="ml-4">(+569) 8361 7524</p></i>
          <i class="fas fa-map-marker-alt mt-5" style="color: red; text-align: right; font-size: 25px;"><p style="display: inline; color: black; font-family: Oswald; font-size: 18px;" class="ml-4">18 de septiembre 2222. Departamento de Educación. Oficina 16.</p></i>
        </div>
      </div>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>

</body>

</html>

fondecyt/templates/colaborador.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    <div class="col-1"></div>
    <div class="col-10" style="text-align: justify; background-color: #ffffff;">
        {% if foto %}
        <img src="{{foto}}" class="img-fluid w-10 mr-3 md-3 mt-3 mb-2" alt="Responsive image" style="float: left; height: 15rem;">
        {% endif %}
        <h3 class="mt-2">{{persona.name}} {{persona.lastname}}</h3>
        <p class="mt-3 mb-4">{{persona.universidad}}</p>
        <p class="mt-3">{{persona.resumen}}</p>  
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}

fondecyt/templates/colaboradores.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    {% for persona in colaboradores %}
    <div class="col-lg-6 col-12">
	    <div class="row">
        <div class="card mb-3" style="width:540px;">
            <a href="{% url 'fondecyt:colaborador' persona.id %}" style="text-decoration: none; color: #000;">
            <div class="row no-gutters">
                <div class="col-md-4 col-4">
                    {% if persona.photo %}
                    <img src="{{persona.photo.url}}" class="card-img card-img-top" alt="...">
                    {% else %}
                    <img src="{% static 'fondecyt/images/perfil.jpg' %}" class="card-img img-fluid card-img-top" alt="...">
                    {% endif %}
                </div>
                <div class="col-md-8 col-8">
                    <div class="card-body">
                            <h5 class="card-title">{{persona.name}} {{persona.lastname}}</h5>
                            <p class="card-text mt-7" style="text-align: justify; color:#5F5757;">{{persona.universidad}}</p>
                            <p class="card-text mt-7" style="text-align: justify; color:#5F5757;">{{persona.info}}</p>
                        </div>
                    </div>
                </div>
            </a>
	</div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

fondecyt/templates/equipo.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    {% for persona in equipo %}
    <div class="col-lg-6 col-12">
	    <div class="row">
        <div class="card mb-3" style="width:540px;">
            <a href="{% url 'fondecyt:integrante' persona.id %}" style="text-decoration: none; color: #000;">
            <div class="row no-gutters">
                <div class="col-md-4 col-4">
                    {% if persona.photo %}
                    <img src="{{persona.photo.url}}" class="card-img card-img-top" alt="...">
                    {% else %}
                    <img src="{% static 'fondecyt/images/perfil.jpg' %}" class="card-img img-fluid card-img-top" alt="...">
                    {% endif %}
                </div>
                <div class="col-md-8 col-8">
                    <div class="card-body">
                            <h5 class="card-title">{{persona.name}} {{persona.lastname}}</h5>
                            <p class="card-text mt-7" style="text-align: justify; color:#5F5757;">{{persona.universidad}}</p>
                            <p class="card-text mt-7" style="text-align: justify; color:#5F5757;">{{persona.info}}</p>
                        </div>
                    </div>
                </div>
            </a>
	</div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

fondecyt/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block partials %}
<div class="jumbotron jumbotron-special">
  <br>
  <br>
  <h1 class="display-4 weight-font">Universidad de tarapacá</h1>
  <br>
  <br>
</div>
{% endblock %}

{% block content_body %}
<div class="row mt-4">
  <div class="col-lg-6 col-12">
    <img src="{% static 'fondecyt/images/afiche.jpg' %}" class="img-fluid w-100 " alt="Responsive image"
      style="float: left;">
  </div>
  <div class="col-lg-6 col-12 mt-5">
    <div class="row">
      <div class="col-12">
        <a href="{% url 'fondecyt:colaboradores' %}" style="text-decoration: none; color: #000;">
          <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-4 col-4">
                <img src="{% static 'fondecyt/images/study.jpg' %}" class="card-img card-img-top" alt="...">
              </div>
              <div class="col-md-8 col-8">
                <div class="card-body">
                  <h5 class="card-title">Colaboradores</h5>
                  <p class="card-text justify-text">Conoce a los academicos que forman parte de este proyecto. </p>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-12">
        <a href="{% url 'fondecyt:instituciones' %}" style="text-decoration: none; color: #000;">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-4 col-4">
              <img src="{% static 'fondecyt/images/instituciones.png' %}" class="card-img card-img-top" alt="...">
            </div>
            <div class="col-md-8 col-8">
              <div class="card-body">
                <h5 class="card-title">Instituciones participantes</h5>
                <p class="card-text justify-text">Conoce las diversas instituciones que han brindado información para llevar a 
                  cabo las investigaciones.
                </p>
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
      <div class="col-12">
        <a href="{% url 'fondecyt:equipo' %}" style="text-decoration: none; color: #000;">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-4 col-4">
              <img src="{% static 'fondecyt/images/equipo.jpg' %}" class="card-img card-img-top" alt="...">
            </div>
            <div class="col-md-8 col-8">
              <div class="card-body">
                <h5 class="card-title">Equipo de investigación</h5>
                <p class="card-text justify-text">Conoce a los academicos que forman parte de este proyecto.</p>
              </div>
            </div>
          </div>
        </div>
        </a>
      </div>
    </div>
  </div>
  <div class="col-lg-6 col-12 mt-4">
    <div class="row">
      {% for noticia in noticias %}
      <div class="col-12">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            {% if noticia.photo %}
            <div class="col-md-4 col-4">
              <img src="{{noticia.photo.url}}" class="card-img card-img-top" alt="...">
            </div>
            {% else %}
            <div class="col-md-4 col-4">
              <img src="{% static 'fondecyt/images/news.jpg' %}" class="card-img card-img-top" alt="...">
            </div>
            {% endif %}
            <div class="col-md-8 col-8">
              <div class="card-body">
                <h5 class="card-title" style="font-size: 15px; text-align: center;">{{noticia.titulo}}</h5>
                <p class="card-text justify-text" style="font-size: 13px;">{{noticia.cabecera}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="col-lg-6 col-12 mt-1">
    <img src="{% static 'fondecyt/images/logoAnid.png' %}" class="img-fluid w-100 " alt="Responsive image"
      style="float: left;">
  </div>
</div>
{% endblock %}

{% block parciales %}
{% endblock%}

fondecyt/templates/instituciones.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    {% for universidad in instituciones %}
    <div class="col-lg-4 col-12">
        <div class="card" style="width: 18rem;">
            {% if universidad.photo %}
            <img src="{{universidad.photo.url}}" class="card-img img-fluid card-img-top" alt="...">
            {% else %}
            <img src="{% static 'fondecyt/images/news.jpg' %}" class="card-img img-fluid card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title" style="font-size: 15px; text-align: center; text"><strong>{{universidad.name}}</strong></h5>
                <p class="card-text mt-2" style="text-align: justify; font-size: 14px;">{{universidad.desc}}</p>
                <a href="{{universidad.web}}" class="btn btn-primary" target="_blank" >Web de la institución</a>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

fondecyt/templates/integrante.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    <div class="col-1"></div>
    <div class="col-10" style="text-align: justify; background-color: #ffffff;">
        {% if foto %}
        <img src="{{foto}}" class="img-fluid w-10 mr-3 md-3 mt-3 mb-2" alt="Responsive image" style="float: left; height: 15rem;">
        {% endif %}
        <h3 class="mt-2">{{persona.name}} {{persona.lastname}}</h3>
        <p class="mt-3 mb-4">{{persona.universidad}}</p>
        <p class="mt-3">{{persona.resumen}}</p>  
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}

fondecyt/templates/noticia.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
    <div class="col-12" style="text-align: justify;">
        <h3 style="text-align: center;">{{noticia.titulo}}</h3>
        {% if foto %}
        <img src="{{foto}}" class="img-fluid w-10 mr-3 md-3 mt-3" alt="Responsive image" style="float: left;">
        {% endif %}
        {% for parrafo in parrafos %}
        <p class="mt-3">{{parrafo}}</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

fondecyt/templates/noticias.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-3">
  <div class="col-lg 6 col-12">
    <img src="{% static 'fondecyt/images/Panel3.jpeg' %}" class="img-fluid w-10 mr-3 md-3 mt-2" alt="Responsive image" style="float: left;">
  </div>
  <div class="col-lg-6 col-12 mt-5">
  {% for noticia in noticias %}
    <div class="card mb-3" style="max-width: 540px;">
      <a href="{% url 'fondecyt:noticia' noticia.id %}" style="text-decoration:none; color: black;">
        <div class="row no-gutters">
          <div class="col-md-4">
            {% if noticia.photo %}
            <img src="{{noticia.photo.url}}" class="card-img img-fluid card-img-top" alt="...">
            {% else %}
            <img src="{% static 'fondecyt/images/news.jpg' %}" class="card-img img-fluid card-img-top" alt="...">
            {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title" style="font-size: 15px; text-align: center; margin-top: -12px;">{{noticia.titulo}}</h5>
              <p class="card-text mt-2" style="text-align: justify; font-size: 14px;">{{noticia.cabecera}}</p>
            </div>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  {% for noticia in noticias2 %}
  <div class="card mb-3 mt-3" style="max-width: 540px;">
    <a href="{% url 'fondecyt:noticia' noticia.id %}" style="text-decoration:none; color: black;">
      <div class="row no-gutters">
        <div class="col-md-4">
          {% if noticia.photo %}
          <img src="{{noticia.photo.url}}" class="card-img img-fluid card-img-top" alt="...">
          {% else %}
          <img src="{% static 'fondecyt/images/news.jpg' %}" class="card-img img-fluid card-img-top" alt="...">
          {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title" style="font-size: 15px; text-align: center; margin-top: -12px;">{{noticia.titulo}}</h5>
            <p class="card-text mt-2" style="text-align: justify; font-size: 14px;">{{noticia.cabecera}}</p>
          </div>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

fondecyt/templates/partials/navbar.html
{% load static %}
<!--<nav class="navbar navbar-expand-lg  border-bottom " style="background-color: #E0E2DB;">
  <ul class="navbar-nav" style="font-size: 0.8rem;">
    <li class="nav-item" style="margin-left: 100px; font-size: 20px;">
      fondecyt
    </li>
    <li class="nav-item ">
    </li>
    <li class="nav-item">
    </li>
  </ul>
</nav>
-->
<nav class="navbar navbar-expand-lg " style="background-color: #FFFFFF;">
  <ul class="navbar-nav mx-auto">
    <li class="nav-item">
      <a href="#">
        <img class="navbar-brand" src="{% static 'fondecyt/images/LOGO-FONDECYT.png' %}" width="300">
      </a>
    </li>
  </ul>
</nav>

  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #F2EDEB;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto ">
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'fondecyt:home' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fondecyt:proyecto' %}">Proyecto</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fondecyt:instituciones' %}">Instituciones participantes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fondecyt:equipo' %}">Equipo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fondecyt:productos'%}">Productos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fondecyt:noticias' %}">Noticias</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fondecyt:colaboradores' %}">Colaboradores</a>
        </li>
      </ul>
    </div>
  </nav>

fondecyt/templates/productos.html
{% extends "base.html" %}
{% load static %}

{% block content_body %}
<div class="row mt-4">
  {% for producto in productos %}
  <div class="card" style="width: 30rem;">
    <div class="card-body">
      <h5 class="card-title" style="text-align: center;">{{producto.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">Por {{producto.autor.name}} {{producto.autor.lastname}}</h6>
      <p class="card-text" style="text-align: justify;">{{producto.description}}</p>
      <a href="{{producto.document.url}}"  target='_blank' class="card-link">Ver archivo</a>
      <div class="text-muted">
        {{producto.uploaded_at}}
      </div>
    </div>
  </div>
    {% endfor %}
</div>
{% endblock %}